# Generated by Django 5.1.1 on 2024-09-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_hamburguesa_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanada',
            name='precio',
            field=models.DecimalField(decimal_places=1024, max_digits=1024),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='precio',
            field=models.FloatField(),
        ),
    ]
