# Generated by Django 5.1.1 on 2024-09-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_alter_empanada_precio_alter_hamburguesa_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanada',
            name='ingredientes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empanada',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empanada',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
